# Generated by Django 4.0 on 2021-12-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=50)),
                ('raw_description', models.TextField()),
                ('raw_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_bio', models.TextField(blank=True, max_length=500)),
                ('supplier_address', models.TextField(blank=True, max_length=200, null=True)),
                ('supplier_contact', models.CharField(blank=True, max_length=14)),
                ('supplier_birthdate', models.DateField(blank=True, null=True)),
                ('supplier_supply', models.TextField()),
                ('supplier_img', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='RawOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.FloatField()),
                ('order_status', models.CharField(default='New', max_length=10)),
                ('item_is', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductionApp.rawmaterial')),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductionApp.supplier')),
            ],
        ),
    ]
