# Generated by Django 4.0 on 2021-12-15 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0002_company_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_email',
            field=models.EmailField(default=models.CharField(max_length=30), max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 15, 8, 46, 56, 635067, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 15, 8, 46, 56, 635067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_website',
            field=models.URLField(null=True),
        ),
    ]
